on: 
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4
      - name: Set up Node.js
        uses: https://data.forgejo.org/actions/setup-node@v4
        with:
          node-version: 24.6.0
      - name: Cache node_modules
        uses: https://data.forgejo.org/actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          CF_ACCOUNT_ANALYTICS_TOKEN: ${{ secrets.CF_ACCOUNT_ANALYTICS_TOKEN }}
          CF_ACCOUNT: ${{ secrets.CF_ACCOUNT }}
          MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
      - name: Deploy
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}